-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.escalations (
  id bigint NOT NULL DEFAULT nextval('escalations_id_seq'::regclass),
  tenant_id uuid NOT NULL,
  session_id uuid,
  reason text NOT NULL,
  contact_info text,
  requested_at timestamp with time zone NOT NULL DEFAULT now(),
  status text NOT NULL DEFAULT 'pending'::text,
  CONSTRAINT escalations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.voices (
  id text NOT NULL,
  display_name text NOT NULL,
  gender text,
  preview_url text,
  artwork_url text,
  enabled boolean NOT NULL DEFAULT true,
  provider text NOT NULL DEFAULT 'uplift'::text,
  provider_voice_id text,
  language text NOT NULL DEFAULT 'ur'::text,
  rollout_state text NOT NULL DEFAULT 'enabled'::text CHECK (rollout_state = ANY (ARRAY['planned'::text, 'testing'::text, 'enabled'::text])),
  CONSTRAINT voices_pkey PRIMARY KEY (id)
);
CREATE TABLE public.tenants (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  hmac_secret_hash text NOT NULL,
  max_concurrent integer NOT NULL DEFAULT 2,
  max_minutes_month integer NOT NULL DEFAULT 100,
  allowed_origins ARRAY NOT NULL DEFAULT '{}'::text[],
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'suspended'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  hmac_secret text,
  CONSTRAINT tenants_pkey PRIMARY KEY (id)
);
CREATE TABLE public.agents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  name text NOT NULL,
  prompt text NOT NULL,
  voice_id text NOT NULL,
  llm_model text NOT NULL DEFAULT 'gemini-2.5-flash'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  agent_language text NOT NULL DEFAULT 'ur'::text,
  stt_provider text NOT NULL DEFAULT 'gladia'::text,
  stt_model text NOT NULL DEFAULT 'default'::text,
  stt_options jsonb NOT NULL DEFAULT '{}'::jsonb,
  llm_provider text NOT NULL DEFAULT 'gemini'::text,
  llm_options jsonb NOT NULL DEFAULT '{}'::jsonb,
  tts_provider text NOT NULL DEFAULT 'uplift'::text,
  tts_voice_id text,
  tts_options jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT agents_pkey PRIMARY KEY (id),
  CONSTRAINT agents_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT agents_voice_id_fkey FOREIGN KEY (voice_id) REFERENCES public.voices(id)
);
CREATE TABLE public.sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  agent_id uuid NOT NULL,
  room_name text NOT NULL UNIQUE,
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  ended_at timestamp with time zone,
  duration_sec integer,
  end_reason text,
  summary text,
  transcript jsonb,
  CONSTRAINT sessions_pkey PRIMARY KEY (id),
  CONSTRAINT sessions_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT sessions_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agents(id)
);
CREATE TABLE public.usage_events (
  id bigint NOT NULL DEFAULT nextval('usage_events_id_seq'::regclass),
  tenant_id uuid NOT NULL,
  session_id uuid,
  kind text NOT NULL CHECK (kind = ANY (ARRAY['stt_sec'::text, 'tts_sec'::text, 'llm_tokens'::text, 'agent_sec'::text])),
  qty numeric NOT NULL,
  at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT usage_events_pkey PRIMARY KEY (id),
  CONSTRAINT usage_events_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT usage_events_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.sessions(id)
);
CREATE TABLE public.quota_state (
  tenant_id uuid NOT NULL,
  concurrent_now integer NOT NULL DEFAULT 0,
  minutes_this_month numeric NOT NULL DEFAULT 0,
  period_start date NOT NULL DEFAULT (date_trunc('month'::text, now()))::date,
  CONSTRAINT quota_state_pkey PRIMARY KEY (tenant_id),
  CONSTRAINT quota_state_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.used_nonces (
  tenant_id uuid NOT NULL,
  nonce text NOT NULL,
  used_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT used_nonces_pkey PRIMARY KEY (tenant_id, nonce),
  CONSTRAINT used_nonces_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.admin_users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL UNIQUE,
  password_hash text NOT NULL,
  totp_secret text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT admin_users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.admin_audit_log (
  id bigint NOT NULL DEFAULT nextval('admin_audit_log_id_seq'::regclass),
  admin_id uuid NOT NULL,
  action text NOT NULL,
  detail jsonb,
  at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT admin_audit_log_pkey PRIMARY KEY (id),
  CONSTRAINT admin_audit_log_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES public.admin_users(id)
);
CREATE TABLE public.mint_rejections (
  id bigint NOT NULL DEFAULT nextval('mint_rejections_id_seq'::regclass),
  tenant_id uuid,
  status integer NOT NULL,
  reason text NOT NULL,
  at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT mint_rejections_pkey PRIMARY KEY (id)
);
CREATE TABLE public.tenant_telnyx_connections (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  label text,
  platform_status text NOT NULL DEFAULT 'not_connected'::text CHECK (platform_status = ANY (ARRAY['not_connected'::text, 'verifying'::text, 'active'::text, 'verification_failed'::text, 'rotation_required'::text, 'permission_failed'::text, 'compromised'::text, 'disabled'::text, 'disconnected'::text])),
  provider_status text,
  encrypted_api_key_ref text,
  key_fingerprint text,
  telnyx_account_id text,
  last_verified_at timestamp with time zone,
  permission_last_checked_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  disabled_at timestamp with time zone,
  disconnected_at timestamp with time zone,
  compromised_at timestamp with time zone,
  retention_until timestamp with time zone,
  deletion_requested_at timestamp with time zone,
  deleted_at timestamp with time zone,
  offboarded_at timestamp with time zone,
  redacted_at timestamp with time zone,
  redaction_reason text,
  CONSTRAINT tenant_telnyx_connections_pkey PRIMARY KEY (id),
  CONSTRAINT tenant_telnyx_connections_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.telnyx_sip_connections (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  telnyx_connection_id uuid NOT NULL,
  provider_sip_connection_id text,
  sip_fqdn text,
  sip_username text,
  encrypted_sip_secret_ref text,
  platform_status text NOT NULL DEFAULT 'draft'::text CHECK (platform_status = ANY (ARRAY['draft'::text, 'pending_verification'::text, 'testing'::text, 'active'::text, 'failed'::text, 'disabled'::text])),
  provider_status text,
  last_verified_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  disabled_at timestamp with time zone,
  retention_until timestamp with time zone,
  deletion_requested_at timestamp with time zone,
  deleted_at timestamp with time zone,
  offboarded_at timestamp with time zone,
  redacted_at timestamp with time zone,
  redaction_reason text,
  CONSTRAINT telnyx_sip_connections_pkey PRIMARY KEY (id),
  CONSTRAINT telnyx_sip_connections_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT telnyx_sip_connections_telnyx_connection_id_fkey FOREIGN KEY (telnyx_connection_id) REFERENCES public.tenant_telnyx_connections(id),
  CONSTRAINT telnyx_sip_connections_telnyx_connection_tenant_fk FOREIGN KEY (telnyx_connection_id) REFERENCES public.tenant_telnyx_connections(id),
  CONSTRAINT telnyx_sip_connections_telnyx_connection_tenant_fk FOREIGN KEY (tenant_id) REFERENCES public.tenant_telnyx_connections(tenant_id)
);
CREATE TABLE public.telnyx_outbound_voice_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  telnyx_connection_id uuid NOT NULL,
  telnyx_sip_connection_id uuid,
  provider_outbound_voice_profile_id text,
  platform_status text NOT NULL DEFAULT 'not_configured'::text CHECK (platform_status = ANY (ARRAY['not_configured'::text, 'configuring'::text, 'active'::text, 'destination_restricted'::text, 'limit_reached'::text, 'verification_required'::text, 'failed'::text, 'disabled'::text])),
  provider_status text,
  allowed_destinations ARRAY NOT NULL DEFAULT '{}'::text[],
  concurrency_limit integer,
  channel_limit integer,
  daily_spending_limit numeric,
  last_verified_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  disabled_at timestamp with time zone,
  retention_until timestamp with time zone,
  deletion_requested_at timestamp with time zone,
  deleted_at timestamp with time zone,
  offboarded_at timestamp with time zone,
  redacted_at timestamp with time zone,
  redaction_reason text,
  CONSTRAINT telnyx_outbound_voice_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT telnyx_outbound_voice_profiles_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT telnyx_outbound_voice_profiles_telnyx_connection_id_fkey FOREIGN KEY (telnyx_connection_id) REFERENCES public.tenant_telnyx_connections(id),
  CONSTRAINT telnyx_outbound_voice_profiles_telnyx_sip_connection_id_fkey FOREIGN KEY (telnyx_sip_connection_id) REFERENCES public.telnyx_sip_connections(id),
  CONSTRAINT telnyx_outbound_voice_profiles_telnyx_connection_tenant_fk FOREIGN KEY (telnyx_connection_id) REFERENCES public.tenant_telnyx_connections(id),
  CONSTRAINT telnyx_outbound_voice_profiles_telnyx_connection_tenant_fk FOREIGN KEY (tenant_id) REFERENCES public.tenant_telnyx_connections(tenant_id),
  CONSTRAINT telnyx_outbound_voice_profiles_sip_connection_tenant_fk FOREIGN KEY (telnyx_sip_connection_id) REFERENCES public.telnyx_sip_connections(id),
  CONSTRAINT telnyx_outbound_voice_profiles_sip_connection_tenant_fk FOREIGN KEY (tenant_id) REFERENCES public.telnyx_sip_connections(tenant_id)
);
CREATE TABLE public.telephony_phone_numbers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  telnyx_connection_id uuid NOT NULL,
  telnyx_sip_connection_id uuid,
  provider_number_id text,
  e164_number text NOT NULL,
  country text,
  number_type text,
  features ARRAY NOT NULL DEFAULT '{}'::text[],
  provisioning_status text NOT NULL DEFAULT 'discovered'::text CHECK (provisioning_status = ANY (ARRAY['discovered'::text, 'import_pending'::text, 'imported'::text, 'purchase_pending'::text, 'purchase_failed'::text, 'owned'::text, 'provider_removed'::text, 'suspended'::text, 'disabled'::text, 'released'::text, 'deleted'::text])),
  routing_status text NOT NULL DEFAULT 'not_configured'::text CHECK (routing_status = ANY (ARRAY['not_configured'::text, 'configuring'::text, 'ready'::text, 'degraded'::text, 'failed'::text, 'disabled'::text])),
  provider_status text,
  assigned_agent_id uuid,
  external_customer_ref text,
  last_synced_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  disabled_at timestamp with time zone,
  retention_until timestamp with time zone,
  deletion_requested_at timestamp with time zone,
  deleted_at timestamp with time zone,
  offboarded_at timestamp with time zone,
  redacted_at timestamp with time zone,
  redaction_reason text,
  CONSTRAINT telephony_phone_numbers_pkey PRIMARY KEY (id),
  CONSTRAINT telephony_phone_numbers_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT telephony_phone_numbers_telnyx_connection_id_fkey FOREIGN KEY (telnyx_connection_id) REFERENCES public.tenant_telnyx_connections(id),
  CONSTRAINT telephony_phone_numbers_telnyx_sip_connection_id_fkey FOREIGN KEY (telnyx_sip_connection_id) REFERENCES public.telnyx_sip_connections(id),
  CONSTRAINT telephony_phone_numbers_assigned_agent_id_fkey FOREIGN KEY (assigned_agent_id) REFERENCES public.agents(id),
  CONSTRAINT telephony_phone_numbers_telnyx_connection_tenant_fk FOREIGN KEY (telnyx_connection_id) REFERENCES public.tenant_telnyx_connections(id),
  CONSTRAINT telephony_phone_numbers_telnyx_connection_tenant_fk FOREIGN KEY (tenant_id) REFERENCES public.tenant_telnyx_connections(tenant_id),
  CONSTRAINT telephony_phone_numbers_sip_connection_tenant_fk FOREIGN KEY (telnyx_sip_connection_id) REFERENCES public.telnyx_sip_connections(id),
  CONSTRAINT telephony_phone_numbers_sip_connection_tenant_fk FOREIGN KEY (tenant_id) REFERENCES public.telnyx_sip_connections(tenant_id),
  CONSTRAINT telephony_phone_numbers_assigned_agent_tenant_fk FOREIGN KEY (assigned_agent_id) REFERENCES public.agents(id),
  CONSTRAINT telephony_phone_numbers_assigned_agent_tenant_fk FOREIGN KEY (tenant_id) REFERENCES public.agents(tenant_id)
);
CREATE TABLE public.livekit_inbound_trunks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  phone_number_id uuid NOT NULL,
  telnyx_connection_id uuid NOT NULL,
  telnyx_sip_connection_id uuid NOT NULL,
  livekit_inbound_trunk_id text,
  platform_status text NOT NULL DEFAULT 'draft'::text CHECK (platform_status = ANY (ARRAY['draft'::text, 'pending_verification'::text, 'testing'::text, 'active'::text, 'failed'::text, 'disabled'::text])),
  provider_status text,
  last_reconciled_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  disabled_at timestamp with time zone,
  retention_until timestamp with time zone,
  deletion_requested_at timestamp with time zone,
  deleted_at timestamp with time zone,
  offboarded_at timestamp with time zone,
  redacted_at timestamp with time zone,
  redaction_reason text,
  CONSTRAINT livekit_inbound_trunks_pkey PRIMARY KEY (id),
  CONSTRAINT livekit_inbound_trunks_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT livekit_inbound_trunks_phone_number_id_fkey FOREIGN KEY (phone_number_id) REFERENCES public.telephony_phone_numbers(id),
  CONSTRAINT livekit_inbound_trunks_telnyx_connection_id_fkey FOREIGN KEY (telnyx_connection_id) REFERENCES public.tenant_telnyx_connections(id),
  CONSTRAINT livekit_inbound_trunks_telnyx_sip_connection_id_fkey FOREIGN KEY (telnyx_sip_connection_id) REFERENCES public.telnyx_sip_connections(id),
  CONSTRAINT livekit_inbound_trunks_phone_number_tenant_fk FOREIGN KEY (phone_number_id) REFERENCES public.telephony_phone_numbers(id),
  CONSTRAINT livekit_inbound_trunks_phone_number_tenant_fk FOREIGN KEY (tenant_id) REFERENCES public.telephony_phone_numbers(tenant_id),
  CONSTRAINT livekit_inbound_trunks_telnyx_connection_tenant_fk FOREIGN KEY (telnyx_connection_id) REFERENCES public.tenant_telnyx_connections(id),
  CONSTRAINT livekit_inbound_trunks_telnyx_connection_tenant_fk FOREIGN KEY (tenant_id) REFERENCES public.tenant_telnyx_connections(tenant_id),
  CONSTRAINT livekit_inbound_trunks_sip_connection_tenant_fk FOREIGN KEY (telnyx_sip_connection_id) REFERENCES public.telnyx_sip_connections(id),
  CONSTRAINT livekit_inbound_trunks_sip_connection_tenant_fk FOREIGN KEY (tenant_id) REFERENCES public.telnyx_sip_connections(tenant_id)
);
CREATE TABLE public.livekit_outbound_trunks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  telnyx_connection_id uuid NOT NULL,
  telnyx_sip_connection_id uuid NOT NULL,
  outbound_voice_profile_record_id uuid NOT NULL,
  livekit_outbound_trunk_id text,
  platform_status text NOT NULL DEFAULT 'draft'::text CHECK (platform_status = ANY (ARRAY['draft'::text, 'pending_verification'::text, 'testing'::text, 'active'::text, 'failed'::text, 'disabled'::text])),
  provider_status text,
  last_reconciled_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  disabled_at timestamp with time zone,
  retention_until timestamp with time zone,
  deletion_requested_at timestamp with time zone,
  deleted_at timestamp with time zone,
  offboarded_at timestamp with time zone,
  redacted_at timestamp with time zone,
  redaction_reason text,
  CONSTRAINT livekit_outbound_trunks_pkey PRIMARY KEY (id),
  CONSTRAINT livekit_outbound_trunks_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT livekit_outbound_trunks_telnyx_connection_id_fkey FOREIGN KEY (telnyx_connection_id) REFERENCES public.tenant_telnyx_connections(id),
  CONSTRAINT livekit_outbound_trunks_telnyx_sip_connection_id_fkey FOREIGN KEY (telnyx_sip_connection_id) REFERENCES public.telnyx_sip_connections(id),
  CONSTRAINT livekit_outbound_trunks_outbound_voice_profile_record_id_fkey FOREIGN KEY (outbound_voice_profile_record_id) REFERENCES public.telnyx_outbound_voice_profiles(id),
  CONSTRAINT livekit_outbound_trunks_telnyx_connection_tenant_fk FOREIGN KEY (telnyx_connection_id) REFERENCES public.tenant_telnyx_connections(id),
  CONSTRAINT livekit_outbound_trunks_telnyx_connection_tenant_fk FOREIGN KEY (tenant_id) REFERENCES public.tenant_telnyx_connections(tenant_id),
  CONSTRAINT livekit_outbound_trunks_sip_connection_tenant_fk FOREIGN KEY (telnyx_sip_connection_id) REFERENCES public.telnyx_sip_connections(id),
  CONSTRAINT livekit_outbound_trunks_sip_connection_tenant_fk FOREIGN KEY (tenant_id) REFERENCES public.telnyx_sip_connections(tenant_id),
  CONSTRAINT livekit_outbound_trunks_voice_profile_tenant_fk FOREIGN KEY (outbound_voice_profile_record_id) REFERENCES public.telnyx_outbound_voice_profiles(id),
  CONSTRAINT livekit_outbound_trunks_voice_profile_tenant_fk FOREIGN KEY (tenant_id) REFERENCES public.telnyx_outbound_voice_profiles(tenant_id)
);
CREATE TABLE public.livekit_sip_dispatch_rules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  phone_number_id uuid NOT NULL,
  inbound_trunk_record_id uuid NOT NULL,
  livekit_sip_dispatch_rule_id text,
  platform_status text NOT NULL DEFAULT 'draft'::text CHECK (platform_status = ANY (ARRAY['draft'::text, 'pending_verification'::text, 'testing'::text, 'active'::text, 'failed'::text, 'disabled'::text])),
  provider_status text,
  last_reconciled_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  disabled_at timestamp with time zone,
  retention_until timestamp with time zone,
  deletion_requested_at timestamp with time zone,
  deleted_at timestamp with time zone,
  offboarded_at timestamp with time zone,
  redacted_at timestamp with time zone,
  redaction_reason text,
  CONSTRAINT livekit_sip_dispatch_rules_pkey PRIMARY KEY (id),
  CONSTRAINT livekit_sip_dispatch_rules_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT livekit_sip_dispatch_rules_phone_number_id_fkey FOREIGN KEY (phone_number_id) REFERENCES public.telephony_phone_numbers(id),
  CONSTRAINT livekit_sip_dispatch_rules_inbound_trunk_record_id_fkey FOREIGN KEY (inbound_trunk_record_id) REFERENCES public.livekit_inbound_trunks(id),
  CONSTRAINT livekit_sip_dispatch_rules_phone_number_tenant_fk FOREIGN KEY (phone_number_id) REFERENCES public.telephony_phone_numbers(id),
  CONSTRAINT livekit_sip_dispatch_rules_phone_number_tenant_fk FOREIGN KEY (tenant_id) REFERENCES public.telephony_phone_numbers(tenant_id),
  CONSTRAINT livekit_sip_dispatch_rules_inbound_trunk_tenant_fk FOREIGN KEY (inbound_trunk_record_id) REFERENCES public.livekit_inbound_trunks(id),
  CONSTRAINT livekit_sip_dispatch_rules_inbound_trunk_tenant_fk FOREIGN KEY (tenant_id) REFERENCES public.livekit_inbound_trunks(tenant_id)
);
CREATE TABLE public.telephony_number_orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  telnyx_connection_id uuid NOT NULL,
  idempotency_key text NOT NULL,
  provider_order_id text,
  selected_e164_number text NOT NULL,
  country text,
  area_code text,
  number_type text,
  features ARRAY NOT NULL DEFAULT '{}'::text[],
  price_amount numeric,
  price_currency text,
  provider_status text CHECK (provider_status IS NULL OR (provider_status = ANY (ARRAY['pending'::text, 'success'::text, 'failure'::text, 'cancelled'::text, 'deleted'::text]))),
  platform_status text NOT NULL DEFAULT 'pending'::text CHECK (platform_status = ANY (ARRAY['pending'::text, 'purchased'::text, 'configuring_routing'::text, 'ready'::text, 'action_required'::text, 'failed'::text, 'cancelled'::text, 'deleted'::text])),
  raw_provider_status text,
  provider_error_payload jsonb,
  error_code text,
  error_message text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  retention_until timestamp with time zone,
  deletion_requested_at timestamp with time zone,
  deleted_at timestamp with time zone,
  offboarded_at timestamp with time zone,
  redacted_at timestamp with time zone,
  redaction_reason text,
  provider_error_payload_access_scope text NOT NULL DEFAULT 'restricted_diagnostic'::text CHECK (provider_error_payload_access_scope = ANY (ARRAY['restricted_diagnostic'::text, 'redacted'::text])),
  provider_error_payload_redacted_at timestamp with time zone,
  provider_error_payload_redaction_reason text,
  CONSTRAINT telephony_number_orders_pkey PRIMARY KEY (id),
  CONSTRAINT telephony_number_orders_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT telephony_number_orders_telnyx_connection_id_fkey FOREIGN KEY (telnyx_connection_id) REFERENCES public.tenant_telnyx_connections(id),
  CONSTRAINT telephony_number_orders_telnyx_connection_tenant_fk FOREIGN KEY (telnyx_connection_id) REFERENCES public.tenant_telnyx_connections(id),
  CONSTRAINT telephony_number_orders_telnyx_connection_tenant_fk FOREIGN KEY (tenant_id) REFERENCES public.tenant_telnyx_connections(tenant_id)
);
CREATE TABLE public.telephony_calls (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  session_id uuid,
  agent_id uuid,
  phone_number_id uuid,
  direction text NOT NULL CHECK (direction = ANY (ARRAY['inbound'::text, 'outbound'::text])),
  room_name text,
  from_number text,
  to_number text,
  recipient text,
  call_context jsonb NOT NULL DEFAULT '{}'::jsonb,
  external_customer_ref text,
  external_workflow_ref text,
  inbound_trunk_record_id uuid,
  outbound_trunk_record_id uuid,
  sip_dispatch_rule_record_id uuid,
  livekit_agent_dispatch_id text,
  livekit_sip_call_id text,
  livekit_sip_call_id_full text,
  sip_trunk_phone_number text,
  raw_livekit_sip_participant_status text,
  platform_status text NOT NULL DEFAULT 'queued'::text CHECK (platform_status = ANY (ARRAY['queued'::text, 'dialing'::text, 'ringing'::text, 'in_progress'::text, 'completed'::text, 'busy'::text, 'no_answer'::text, 'failed'::text, 'cancelled'::text])),
  provider_status text,
  outcome text,
  error_code text,
  error_message text,
  quota_reserved_at timestamp with time zone,
  quota_released_at timestamp with time zone,
  usage_recorded_at timestamp with time zone,
  started_at timestamp with time zone,
  answered_at timestamp with time zone,
  ended_at timestamp with time zone,
  duration_sec integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  retention_until timestamp with time zone,
  deletion_requested_at timestamp with time zone,
  deleted_at timestamp with time zone,
  offboarded_at timestamp with time zone,
  redacted_at timestamp with time zone,
  redaction_reason text,
  export_requested_at timestamp with time zone,
  export_completed_at timestamp with time zone,
  last_access_audited_at timestamp with time zone,
  CONSTRAINT telephony_calls_pkey PRIMARY KEY (id),
  CONSTRAINT telephony_calls_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT telephony_calls_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.sessions(id),
  CONSTRAINT telephony_calls_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agents(id),
  CONSTRAINT telephony_calls_phone_number_id_fkey FOREIGN KEY (phone_number_id) REFERENCES public.telephony_phone_numbers(id),
  CONSTRAINT telephony_calls_inbound_trunk_record_id_fkey FOREIGN KEY (inbound_trunk_record_id) REFERENCES public.livekit_inbound_trunks(id),
  CONSTRAINT telephony_calls_outbound_trunk_record_id_fkey FOREIGN KEY (outbound_trunk_record_id) REFERENCES public.livekit_outbound_trunks(id),
  CONSTRAINT telephony_calls_sip_dispatch_rule_record_id_fkey FOREIGN KEY (sip_dispatch_rule_record_id) REFERENCES public.livekit_sip_dispatch_rules(id),
  CONSTRAINT telephony_calls_session_tenant_fk FOREIGN KEY (session_id) REFERENCES public.sessions(id),
  CONSTRAINT telephony_calls_session_tenant_fk FOREIGN KEY (tenant_id) REFERENCES public.sessions(tenant_id),
  CONSTRAINT telephony_calls_agent_tenant_fk FOREIGN KEY (agent_id) REFERENCES public.agents(id),
  CONSTRAINT telephony_calls_agent_tenant_fk FOREIGN KEY (tenant_id) REFERENCES public.agents(tenant_id),
  CONSTRAINT telephony_calls_phone_number_tenant_fk FOREIGN KEY (phone_number_id) REFERENCES public.telephony_phone_numbers(id),
  CONSTRAINT telephony_calls_phone_number_tenant_fk FOREIGN KEY (tenant_id) REFERENCES public.telephony_phone_numbers(tenant_id),
  CONSTRAINT telephony_calls_inbound_trunk_tenant_fk FOREIGN KEY (inbound_trunk_record_id) REFERENCES public.livekit_inbound_trunks(id),
  CONSTRAINT telephony_calls_inbound_trunk_tenant_fk FOREIGN KEY (tenant_id) REFERENCES public.livekit_inbound_trunks(tenant_id),
  CONSTRAINT telephony_calls_outbound_trunk_tenant_fk FOREIGN KEY (outbound_trunk_record_id) REFERENCES public.livekit_outbound_trunks(id),
  CONSTRAINT telephony_calls_outbound_trunk_tenant_fk FOREIGN KEY (tenant_id) REFERENCES public.livekit_outbound_trunks(tenant_id),
  CONSTRAINT telephony_calls_sip_dispatch_rule_tenant_fk FOREIGN KEY (sip_dispatch_rule_record_id) REFERENCES public.livekit_sip_dispatch_rules(id),
  CONSTRAINT telephony_calls_sip_dispatch_rule_tenant_fk FOREIGN KEY (tenant_id) REFERENCES public.livekit_sip_dispatch_rules(tenant_id)
);
CREATE TABLE public.telephony_call_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  telephony_call_id uuid NOT NULL,
  source text NOT NULL,
  event_type text NOT NULL,
  provider_event_id text,
  internal_stage text,
  payload jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  retention_until timestamp with time zone,
  deletion_requested_at timestamp with time zone,
  deleted_at timestamp with time zone,
  offboarded_at timestamp with time zone,
  redacted_at timestamp with time zone,
  redaction_reason text,
  payload_access_scope text NOT NULL DEFAULT 'restricted_diagnostic'::text CHECK (payload_access_scope = ANY (ARRAY['restricted_diagnostic'::text, 'redacted'::text])),
  payload_redacted_at timestamp with time zone,
  payload_redaction_reason text,
  CONSTRAINT telephony_call_events_pkey PRIMARY KEY (id),
  CONSTRAINT telephony_call_events_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT telephony_call_events_telephony_call_id_fkey FOREIGN KEY (telephony_call_id) REFERENCES public.telephony_calls(id),
  CONSTRAINT telephony_call_events_telephony_call_tenant_fk FOREIGN KEY (telephony_call_id) REFERENCES public.telephony_calls(id),
  CONSTRAINT telephony_call_events_telephony_call_tenant_fk FOREIGN KEY (tenant_id) REFERENCES public.telephony_calls(tenant_id)
);
CREATE TABLE public.telephony_idempotency_keys (
  tenant_id uuid NOT NULL,
  idempotency_key text NOT NULL,
  action text NOT NULL,
  request_hash text NOT NULL,
  response_body jsonb,
  platform_status text NOT NULL DEFAULT 'pending'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  completed_at timestamp with time zone,
  retention_until timestamp with time zone,
  deletion_requested_at timestamp with time zone,
  deleted_at timestamp with time zone,
  offboarded_at timestamp with time zone,
  redacted_at timestamp with time zone,
  redaction_reason text,
  CONSTRAINT telephony_idempotency_keys_pkey PRIMARY KEY (tenant_id, idempotency_key, action),
  CONSTRAINT telephony_idempotency_keys_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.telephony_audit_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  actor_type text NOT NULL,
  actor_id text,
  action text NOT NULL,
  target_type text NOT NULL,
  target_id text,
  detail jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  retention_until timestamp with time zone,
  deletion_requested_at timestamp with time zone,
  deleted_at timestamp with time zone,
  offboarded_at timestamp with time zone,
  redacted_at timestamp with time zone,
  redaction_reason text,
  request_id text,
  access_reason text,
  export_id text,
  restricted_target boolean NOT NULL DEFAULT false,
  detail_redacted_at timestamp with time zone,
  detail_redaction_reason text,
  CONSTRAINT telephony_audit_log_pkey PRIMARY KEY (id),
  CONSTRAINT telephony_audit_log_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);