"""Tenant-facing dashboard backend/API layer.

Separate FastAPI app for tenant-scoped management APIs. This intentionally does NOT reuse
admin/ or control_plane/ routes:
- admin is a super-admin domain with separate auth and full-system visibility
- control_plane is the session mint/refresh path
- tenant_portal_api is the tenant self-service management surface
"""

from __future__ import annotations

import os
import secrets as _pysecrets
import sys
from pathlib import Path

import psycopg
from dotenv import dotenv_values
from fastapi import FastAPI, Header, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "scripts"))
try:
    from scripts.dbconn import conn_kwargs
except ImportError:
    from dbconn import conn_kwargs  # type: ignore # noqa: E402

from .auth import TenantAuthError, login as tenant_login, verify_tenant_jwt
from . import queries

_ROOT = Path(__file__).resolve().parent.parent
_ENV_PATH = _ROOT / ".env.local"


def _ensure_portal_jwt_secret() -> str:
    env = dotenv_values(_ENV_PATH)
    val = os.environ.get("TENANT_PORTAL_JWT_SECRET") or env.get("TENANT_PORTAL_JWT_SECRET")
    if val:
        return val
    generated = _pysecrets.token_hex(32)
    with open(_ENV_PATH, "a", encoding="utf-8") as f:
        f.write(
            "\n# auto-generated by tenant_portal_api/app.py on 2026-07-21 — "
            "human should rotate/replace if desired\n"
            f"TENANT_PORTAL_JWT_SECRET={generated}\n"
        )
    return generated


TENANT_PORTAL_JWT_SECRET = _ensure_portal_jwt_secret()
DEFAULT_PORTAL_ORIGINS = "http://localhost:3000,http://localhost:5173"
TENANT_PORTAL_ORIGINS = [
    o.strip()
    for o in os.environ.get(
        "TENANT_PORTAL_ORIGINS",
        dotenv_values(_ENV_PATH).get("TENANT_PORTAL_ORIGINS", DEFAULT_PORTAL_ORIGINS),
    ).split(",")
    if o.strip()
]

app = FastAPI(title="UVA tenant portal API")
app.add_middleware(
    CORSMiddleware,
    allow_origins=TENANT_PORTAL_ORIGINS,
    allow_credentials=True,
    allow_methods=["GET", "POST", "PATCH"],
    allow_headers=["Authorization", "Content-Type"],
)


class TenantLoginBody(BaseModel):
    tenant_id: str = Field(..., min_length=1)
    tenant_secret: str = Field(..., min_length=1)


class CreateAgentBody(BaseModel):
    name: str = Field(..., min_length=1)
    prompt: str = Field(..., min_length=1)
    voice_id: str = Field(..., min_length=1)
    llm_model: str = Field(default="gemini-2.5-flash", min_length=1)


class UpdateAgentBody(BaseModel):
    name: str | None = Field(default=None, min_length=1)
    prompt: str | None = Field(default=None, min_length=1)
    voice_id: str | None = Field(default=None, min_length=1)
    llm_model: str | None = Field(default=None, min_length=1)


def _conn() -> psycopg.Connection:
    return psycopg.connect(**conn_kwargs(), connect_timeout=10)


def _require_tenant(authorization: str | None) -> dict:
    if not authorization or not authorization.startswith("Bearer "):
        raise HTTPException(status_code=401, detail="missing bearer token")
    token = authorization[len("Bearer ") :].strip()
    try:
        return verify_tenant_jwt(token, TENANT_PORTAL_JWT_SECRET)
    except TenantAuthError as e:
        raise HTTPException(status_code=e.status, detail=e.reason) from e


@app.get("/healthz")
def tenant_portal_health():
    return {"status": "ok", "service": "uva-tenant-portal-api"}


@app.post("/portal/login")
def portal_login(body: TenantLoginBody):
    try:
        with _conn() as conn:
            return tenant_login(
                conn,
                tenant_id=body.tenant_id,
                tenant_secret=body.tenant_secret,
                jwt_secret=TENANT_PORTAL_JWT_SECRET,
            )
    except TenantAuthError as e:
        raise HTTPException(status_code=e.status, detail=e.reason) from e


@app.get("/portal/agents")
def list_agents_route(authorization: str | None = Header(default=None)):
    claims = _require_tenant(authorization)
    with _conn() as conn:
        return queries.list_agents(conn, claims["sub"])


@app.post("/portal/agents")
def create_agent_route(
    body: CreateAgentBody, authorization: str | None = Header(default=None)
):
    claims = _require_tenant(authorization)
    with _conn() as conn:
        created = queries.create_agent(
            conn,
            claims["sub"],
            name=body.name,
            prompt=body.prompt,
            voice_id=body.voice_id,
            llm_model=body.llm_model,
        )
        conn.commit()
        return created


@app.patch("/portal/agents/{agent_id}")
def update_agent_route(
    agent_id: str,
    body: UpdateAgentBody,
    authorization: str | None = Header(default=None),
):
    claims = _require_tenant(authorization)
    with _conn() as conn:
        try:
            updated = queries.update_agent(
                conn,
                claims["sub"],
                agent_id,
                name=body.name,
                prompt=body.prompt,
                voice_id=body.voice_id,
                llm_model=body.llm_model,
            )
            conn.commit()
            return updated
        except ValueError as e:
            raise HTTPException(status_code=404, detail=str(e)) from e


@app.get("/portal/credentials")
def credentials_route(authorization: str | None = Header(default=None)):
    claims = _require_tenant(authorization)
    with _conn() as conn:
        try:
            return queries.get_credentials(conn, claims["sub"])
        except ValueError as e:
            raise HTTPException(status_code=404, detail=str(e)) from e


@app.get("/portal/sessions")
def sessions_route(
    limit: int = 50, authorization: str | None = Header(default=None)
):
    claims = _require_tenant(authorization)
    with _conn() as conn:
        return queries.list_recent_sessions(conn, claims["sub"], limit=limit)


@app.get("/portal/usage-summary")
def usage_summary_route(
    days: int = 30, authorization: str | None = Header(default=None)
):
    claims = _require_tenant(authorization)
    with _conn() as conn:
        try:
            return queries.usage_summary(conn, claims["sub"], days=days)
        except ValueError as e:
            raise HTTPException(status_code=404, detail=str(e)) from e
