#!/usr/bin/env python3
"""Regenerate supabase/SCHEMA.md and supabase/RLS.md from the live dev database.

Read-only mirror of the live schema (docs/33-GUIDE-SUPABASE.md §5). These files are
AUTO-GENERATED — never hand-edit them; run `make db-inspect` to refresh. The Phase 1
gate requires SCHEMA.md to match live, i.e. re-running this leaves no git diff.

Note: the guide's intended mechanism is the read-only `db-inspector` subagent over a
scoped Supabase MCP. That subagent is not dispatchable in this harness, so this script
performs the equivalent READ-ONLY introspection (SELECTs against pg_catalog /
information_schema only) via scripts/dbconn.py. DEV only.
"""

from __future__ import annotations

import sys
from pathlib import Path

import psycopg

sys.path.insert(0, str(Path(__file__).resolve().parent))
from dbconn import conn_kwargs  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
SUPA = ROOT / "supabase"


def _tables(cur) -> list[str]:
    return [
        r[0]
        for r in cur.execute(
            "select tablename from pg_tables where schemaname='public' order by tablename"
        ).fetchall()
    ]


def build_schema_md(cur) -> str:
    out = [
        "# supabase/SCHEMA.md — AUTO-GENERATED by scripts/db_inspect.py. Do not hand-edit.",
        "Read-only mirror of the live dev schema (public). Regenerate: `make db-inspect`.",
        "",
    ]
    for t in _tables(cur):
        out.append(f"## table: {t}")
        out.append("| column | type | nullable | default |")
        out.append("|---|---|---|---|")
        cols = cur.execute(
            """select column_name, data_type, is_nullable, coalesce(column_default, '')
               from information_schema.columns
               where table_schema='public' and table_name=%s
               order by ordinal_position""",
            (t,),
        ).fetchall()
        for name, typ, nullable, default in cols:
            out.append(f"| {name} | {typ} | {nullable} | {default} |")
        fks = cur.execute(
            """select kcu.column_name, ccu.table_name, ccu.column_name
               from information_schema.table_constraints tc
               join information_schema.key_column_usage kcu on kcu.constraint_name=tc.constraint_name
               join information_schema.constraint_column_usage ccu on ccu.constraint_name=tc.constraint_name
               where tc.constraint_type='FOREIGN KEY' and tc.table_schema='public' and tc.table_name=%s
               order by kcu.column_name""",
            (t,),
        ).fetchall()
        for col, ftab, fcol in fks:
            out.append(f"- FK: {col} -> {ftab}({fcol})")
        idx = cur.execute(
            "select indexname from pg_indexes where schemaname='public' and tablename=%s order by indexname",
            (t,),
        ).fetchall()
        for (name,) in idx:
            out.append(f"- index: {name}")
        out.append("")
    return "\n".join(out) + "\n"


def build_rls_md(cur) -> str:
    out = [
        "# supabase/RLS.md — AUTO-GENERATED by scripts/db_inspect.py. Do not hand-edit.",
        "Read-only mirror of live RLS state. Regenerate: `make db-inspect`.",
        "",
    ]
    rls = dict(
        cur.execute(
            "select tablename, rowsecurity from pg_tables where schemaname='public'"
        ).fetchall()
    )
    for t in _tables(cur):
        out.append(f"## {t}  (RLS: {'ENABLED' if rls.get(t) else 'DISABLED'})")
        pols = cur.execute(
            """select policyname, cmd, coalesce(qual,''), coalesce(with_check,'')
               from pg_policies where schemaname='public' and tablename=%s
               order by policyname""",
            (t,),
        ).fetchall()
        if not pols:
            out.append("- (no policies)")
        for name, cmd, qual, check in pols:
            line = f"- policy {name} [{cmd}]"
            if qual:
                line += f" USING ({qual})"
            if check:
                line += f" WITH CHECK ({check})"
            out.append(line)
        out.append("")
    return "\n".join(out) + "\n"


def main() -> int:
    with psycopg.connect(**conn_kwargs(), connect_timeout=30, autocommit=True) as conn:
        cur = conn.cursor()
        (SUPA / "SCHEMA.md").write_text(build_schema_md(cur), encoding="utf-8")
        (SUPA / "RLS.md").write_text(build_rls_md(cur), encoding="utf-8")
    print("db-inspect: wrote supabase/SCHEMA.md and supabase/RLS.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
