#!/usr/bin/env python3
"""Fetch ElevenLabs' full English voice catalogue (GET /v2/voices, a free/metadata endpoint —
separate from TTS-generation's per-character billing) and generate the seed migration.
Voice-catalogue expansion follow-up to Phase 6d
(docs/UKASHA_AGENT_FACING_MULTIPLE_PROVIDERS_PLAN.md, ADR-036), human-approved scope: all English
voices across every en TTS provider. Requires the `voices_read` permission on ELEVEN_API_KEY (a
real gap this script's first run surfaced — the key was originally scoped to Text-to-Speech only).

    python scripts/fetch_elevenlabs_voices.py --write-migration supabase/migrations/0024_seed_elevenlabs_all_english_voices.sql
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))


def _slugify(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


def fetch_all_english_voices(api_key: str) -> list[dict]:
    all_voices: list[dict] = []
    next_page_token = None
    while True:
        url = "https://api.elevenlabs.io/v2/voices?page_size=100"
        if next_page_token:
            url += f"&page_token={next_page_token}"
        req = urllib.request.Request(url, headers={"xi-api-key": api_key})
        with urllib.request.urlopen(req, timeout=15) as resp:
            data = json.loads(resp.read())
        all_voices.extend(data.get("voices", []))
        if not data.get("has_more"):
            break
        next_page_token = data.get("next_page_token")
        if not next_page_token:
            break
    return [v for v in all_voices if v.get("labels", {}).get("language") == "en"]


def build_rows(voices: list[dict]) -> list[tuple[str, str, str]]:
    seen_ids: dict[str, int] = {}
    rows = []
    for v in voices:
        base_id = f"elevenlabs-{_slugify(v['name'].split(' - ')[0])}"
        count = seen_ids.get(base_id, 0)
        seen_ids[base_id] = count + 1
        vid = base_id if count == 0 else f"{base_id}-{v['voice_id'][:8].lower()}"
        display_name = v["name"].replace("'", "''")
        rows.append((vid, display_name, v["voice_id"]))
    return rows


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--write-migration", required=True, help="path to write the .sql migration"
    )
    args = ap.parse_args()

    from dotenv import load_dotenv

    load_dotenv(ROOT / ".env.local")
    api_key = os.environ.get("ELEVEN_API_KEY")
    if not api_key:
        print("ELEVEN_API_KEY not set", file=sys.stderr)
        return 1

    voices = fetch_all_english_voices(api_key)
    rows = build_rows(voices)
    print(f"Fetched {len(voices)} English ElevenLabs voices, {len(rows)} rows to seed.")

    values_sql = ",\n".join(
        f"  ('{vid}', '{display_name}', 'elevenlabs', '{provider_voice_id}', 'en', 'enabled', true)"
        for vid, display_name, provider_voice_id in rows
    )

    sql = f"""-- {Path(args.write_migration).name} — voice-catalogue expansion, follow-up to Phase 6d
-- (docs/UKASHA_AGENT_FACING_MULTIPLE_PROVIDERS_PLAN.md, ADR-036). Additive only, idempotent
-- (ON CONFLICT DO NOTHING) — no destructive statements.
--
-- Seeds ElevenLabs' full ENGLISH voice catalogue ({len(rows)} voices — this account's premade
-- set; ElevenLabs' /v2/voices returns voices belonging to the authenticated account, not the
-- entire public shared-voice library, which is a different endpoint), fetched live from
-- GET https://api.elevenlabs.io/v2/voices (a free/metadata endpoint, confirmed separate from
-- TTS-generation's per-character billing) via scripts/fetch_elevenlabs_voices.py. Human-approved
-- scope: all English voices across every en TTS provider, not a curated subset. `id` slugs are
-- generated by slugifying each voice's real first name (ElevenLabs names are "Name - description"),
-- disambiguated with the real vendor voice_id's first 8 characters on collision — not invented.
--
-- Seeded as enabled at the voice-row level; actual tenant-facing availability is still gated by
-- worker/providers/capabilities.py's PROVIDER-level rollout_state (`en.tts.elevenlabs` is already
-- `enabled`, Phase 6d), so these become immediately selectable.

insert into voices (id, display_name, provider, provider_voice_id, language, rollout_state, enabled)
values
{values_sql}
on conflict (id) do nothing;
"""
    out_path = ROOT / args.write_migration
    out_path.write_text(sql, encoding="utf-8")
    print(f"Wrote {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
