#!/usr/bin/env python3
"""Fetch Cartesia's full English voice catalogue (GET /voices, a free/metadata endpoint —
confirmed separate from TTS-generation billing, docs.cartesia.ai) and generate the seed
migration. Voice-catalogue expansion follow-up to Phase 6f
(docs/UKASHA_AGENT_FACING_MULTIPLE_PROVIDERS_PLAN.md, ADR-036), human-approved scope: all English
voices across every en TTS provider, not a curated subset.

    python scripts/fetch_cartesia_voices.py --write-migration supabase/migrations/0023_seed_cartesia_all_english_voices.sql
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))


def _slugify(name: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")
    return s


def fetch_all_english_voices(api_key: str) -> list[dict]:
    all_voices: list[dict] = []
    starting_after = None
    while True:
        url = "https://api.cartesia.ai/voices?limit=100"
        if starting_after:
            url += f"&starting_after={starting_after}"
        req = urllib.request.Request(
            url,
            headers={
                "Authorization": f"Bearer {api_key}",
                "Cartesia-Version": "2025-04-16",
            },
        )
        with urllib.request.urlopen(req, timeout=15) as resp:
            data = json.loads(resp.read())
        batch = data.get("data", [])
        all_voices.extend(batch)
        if not data.get("has_more") or not batch:
            break
        starting_after = batch[-1]["id"]
    return [v for v in all_voices if v.get("language") == "en"]


def build_rows(voices: list[dict]) -> list[tuple[str, str, str]]:
    """Returns (id, display_name, provider_voice_id) rows, deduping id collisions with a
    short suffix from the real vendor UUID."""
    seen_ids: dict[str, int] = {}
    rows = []
    for v in voices:
        base_id = f"cartesia-{_slugify(v['name'])}"
        count = seen_ids.get(base_id, 0)
        seen_ids[base_id] = count + 1
        vid = base_id if count == 0 else f"{base_id}-{v['id'][:8]}"
        display_name = v["name"].replace("'", "''")
        rows.append((vid, display_name, v["id"]))
    return rows


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--write-migration", required=True, help="path to write the .sql migration"
    )
    args = ap.parse_args()

    from dotenv import load_dotenv

    load_dotenv(ROOT / ".env.local")
    api_key = os.environ.get("CARTESIA_API_KEY")
    if not api_key:
        print("CARTESIA_API_KEY not set", file=sys.stderr)
        return 1

    voices = fetch_all_english_voices(api_key)
    rows = build_rows(voices)
    print(f"Fetched {len(voices)} English Cartesia voices, {len(rows)} rows to seed.")

    values_sql = ",\n".join(
        f"  ('{vid}', '{display_name}', 'cartesia', '{provider_voice_id}', 'en', 'enabled', true)"
        for vid, display_name, provider_voice_id in rows
    )

    sql = f"""-- {Path(args.write_migration).name} — voice-catalogue expansion, follow-up to Phase 6f
-- (docs/UKASHA_AGENT_FACING_MULTIPLE_PROVIDERS_PLAN.md, ADR-036). Additive only, idempotent
-- (ON CONFLICT DO NOTHING) — no destructive statements.
--
-- Seeds Cartesia's full ENGLISH voice catalogue ({len(rows)} voices), fetched live from
-- GET https://api.cartesia.ai/voices (a free/metadata endpoint, confirmed separate from
-- TTS-generation's per-character billing) via scripts/fetch_cartesia_voices.py. Human-approved
-- scope: all English voices across every en TTS provider, not a curated subset. `id` slugs are
-- generated by slugifying each voice's real display name, disambiguated with the real vendor
-- UUID's first 8 characters on collision — not invented.
--
-- Seeded as enabled at the voice-row level; actual tenant-facing availability is still gated by
-- worker/providers/capabilities.py's PROVIDER-level rollout_state (`en.tts.cartesia` is already
-- `enabled`, Phase 6c), so these become immediately selectable.

insert into voices (id, display_name, provider, provider_voice_id, language, rollout_state, enabled)
values
{values_sql}
on conflict (id) do nothing;
"""
    out_path = ROOT / args.write_migration
    out_path.write_text(sql, encoding="utf-8")
    print(f"Wrote {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
