-- 0024_seed_elevenlabs_all_english_voices.sql — voice-catalogue expansion, follow-up to Phase 6d
-- (docs/UKASHA_AGENT_FACING_MULTIPLE_PROVIDERS_PLAN.md, ADR-036). Additive only, idempotent
-- (ON CONFLICT DO NOTHING) — no destructive statements.
--
-- Seeds ElevenLabs' full ENGLISH voice catalogue (21 voices — this account's premade
-- set; ElevenLabs' /v2/voices returns voices belonging to the authenticated account, not the
-- entire public shared-voice library, which is a different endpoint), fetched live from
-- GET https://api.elevenlabs.io/v2/voices (a free/metadata endpoint, confirmed separate from
-- TTS-generation's per-character billing) via scripts/fetch_elevenlabs_voices.py. Human-approved
-- scope: all English voices across every en TTS provider, not a curated subset. `id` slugs are
-- generated by slugifying each voice's real first name (ElevenLabs names are "Name - description"),
-- disambiguated with the real vendor voice_id's first 8 characters on collision — not invented.
--
-- Seeded as enabled at the voice-row level; actual tenant-facing availability is still gated by
-- worker/providers/capabilities.py's PROVIDER-level rollout_state (`en.tts.elevenlabs` is already
-- `enabled`, Phase 6d), so these become immediately selectable.

insert into voices (id, display_name, provider, provider_voice_id, language, rollout_state, enabled)
values
  ('elevenlabs-bella', 'Bella - Professional, Bright, Warm', 'elevenlabs', 'hpp4J3VqNfWAUOO0d1Us', 'en', 'enabled', true),
  ('elevenlabs-roger', 'Roger - Laid-Back, Casual, Resonant', 'elevenlabs', 'CwhRBWXzGAHq8TQ4Fs17', 'en', 'enabled', true),
  ('elevenlabs-sarah', 'Sarah - Mature, Reassuring, Confident', 'elevenlabs', 'EXAVITQu4vr4xnSDxMaL', 'en', 'enabled', true),
  ('elevenlabs-laura', 'Laura - Enthusiast, Quirky Attitude', 'elevenlabs', 'FGY2WhTYpPnrIDTdsKH5', 'en', 'enabled', true),
  ('elevenlabs-charlie', 'Charlie - Deep, Confident, Energetic', 'elevenlabs', 'IKne3meq5aSn9XLyUdCD', 'en', 'enabled', true),
  ('elevenlabs-george', 'George - Warm, Captivating Storyteller', 'elevenlabs', 'JBFqnCBsd6RMkjVDRZzb', 'en', 'enabled', true),
  ('elevenlabs-callum', 'Callum - Husky Trickster', 'elevenlabs', 'N2lVS1w4EtoT3dr4eOWO', 'en', 'enabled', true),
  ('elevenlabs-river', 'River - Relaxed, Neutral, Informative', 'elevenlabs', 'SAz9YHcvj6GT2YYXdXww', 'en', 'enabled', true),
  ('elevenlabs-harry', 'Harry - Fierce Warrior', 'elevenlabs', 'SOYHLrjzK2X1ezoPC6cr', 'en', 'enabled', true),
  ('elevenlabs-liam', 'Liam - Energetic, Social Media Creator', 'elevenlabs', 'TX3LPaxmHKxFdv7VOQHJ', 'en', 'enabled', true),
  ('elevenlabs-alice', 'Alice - Clear, Engaging Educator', 'elevenlabs', 'Xb7hH8MSUJpSbSDYk0k2', 'en', 'enabled', true),
  ('elevenlabs-matilda', 'Matilda - Knowledgable, Professional', 'elevenlabs', 'XrExE9yKIg1WjnnlVkGX', 'en', 'enabled', true),
  ('elevenlabs-will', 'Will - Relaxed Optimist', 'elevenlabs', 'bIHbv24MWmeRgasZH58o', 'en', 'enabled', true),
  ('elevenlabs-jessica', 'Jessica - Playful, Bright, Warm', 'elevenlabs', 'cgSgspJ2msm6clMCkdW9', 'en', 'enabled', true),
  ('elevenlabs-eric', 'Eric - Smooth, Trustworthy', 'elevenlabs', 'cjVigY5qzO86Huf0OWal', 'en', 'enabled', true),
  ('elevenlabs-chris', 'Chris - Charming, Down-to-Earth', 'elevenlabs', 'iP95p4xoKVk53GoZ742B', 'en', 'enabled', true),
  ('elevenlabs-brian', 'Brian - Deep, Resonant and Comforting', 'elevenlabs', 'nPczCjzI2devNBz1zQrb', 'en', 'enabled', true),
  ('elevenlabs-daniel', 'Daniel - Steady Broadcaster', 'elevenlabs', 'onwK4e9ZLuTAKqWW03F9', 'en', 'enabled', true),
  ('elevenlabs-lily', 'Lily - Velvety Actress', 'elevenlabs', 'pFZP5JQG7iQjIQuC4Bku', 'en', 'enabled', true),
  ('elevenlabs-adam', 'Adam - Dominant, Firm', 'elevenlabs', 'pNInz6obpgDQGcFmaJgB', 'en', 'enabled', true),
  ('elevenlabs-bill', 'Bill - Wise, Mature, Balanced', 'elevenlabs', 'pqHfZKP75CvOlQylNhV4', 'en', 'enabled', true)
on conflict (id) do nothing;
